defaults: &defaults
  working_directory: ~/circleci-demo-workflows
  steps:
    - checkout
    - run:
        name: Install & Update the Bundles
        command: |
          gem install bundler
          bundle update || bundle install --jobs 16 --retry 3 --path vendor/bundle
          bundle update && bundle install --jobs 12 --retry 3 --path vendor/bundle
    - run:
        name: git diff
        command: |
          [ ! -d "/tmp" ] && mkdir -p /tmp
          git diff Gem* >> /tmp/diff.txt
          cat /tmp/diff.txt || echo "diff not found"
        no_output_timeout: 2m
    - run:
        name: Rake Test
        command: |
          bundle exec rake db:create db:schema:load
          bundle exec rake --trace || echo "Rake test failed for some reason"

version: 2.0

jobs:
  ruby22:
    docker:
      - image: circleci/ruby:2.2-node
      - image: circleci/postgres:9.4-alpine
    <<: *defaults

  ruby23:
    docker:
      - image: circleci/ruby:2.3-node
      - image: circleci/postgres:9.4-alpine
    <<: *defaults

  ruby24:
    docker:
      - image: circleci/ruby:2.4-node
      - image: circleci/postgres:9.4-alpine
    <<: *defaults

  ruby25:
    docker:
      - image: circleci/ruby:2.5-node
      - image: circleci/postgres:9.5-alpine
    <<: *defaults

workflows:
  version: 2
  build:
    jobs:
      - "ruby22"
      - "ruby23"
      - "ruby24"
      - "ruby25"
