defaults: &defaults
  working_directory: ~/circleci-demo-workflows
  steps:
    - checkout
    - run:
        name: Install & Update the Bundles
        command: |
          gem install bundler
          bundle update --all --jobs 12
          bundle install --no-cache --jobs 8 --retry 3 --path vendor/bundle
    - run:
        name: git diff
        command: |
          [ ! -d "/tmp"] && mkdir -p /tmp
          git diff Gem* > /tmp/diff.txt
          cat /tmp/diff.txt
        no_output_timeout: 1m
    - run:
        name: Rake Test
        command: |
          bundle exec rake db:create db:schema:load
          bundle exec rake --trace || echo "Rake test failed for some reason"

version: 2.0

jobs:
  ruby23:
    docker:
      - image: circleci/ruby:2.3-node
      - image: circleci/postgres:9.4-alpine
    <<: *defaults

  ruby24:
    docker:
      - image: circleci/ruby:2.4-node
      - image: circleci/postgres:9.4-alpine
    <<: *defaults

  ruby25:
    docker:
      - image: circleci/ruby:2.5-node
      - image: circleci/postgres:9.5-alpine
    <<: *defaults

  ruby26:
    docker:
      - image: circleci/ruby:2.6-node
      - image: circleci/postgres:9.5-alpine
    <<: *defaults

workflows:
  version: 2
  build:
    jobs:
      - "ruby23"
      - "ruby24"
      - "ruby25"
      - "ruby26"
