defaults: &defaults
  working_directory: ~/circleci-demo-workflows
  steps:
    - checkout
    - run:
        name: Install the Bundle Dependencies
        command: |
          gem install bundler
          bundle install --no-cache --jobs 8 --retry 3 --path vendor/bundle
    - run:
        name: Rake Test
        command: |
          bundle exec rake db:create db:schema:load
          bundle exec rake --trace

version: 2

jobs:

  master-ruby26:
    docker:
      - image: circleci/ruby:2.6-node
      - image: circleci/postgres:9.5-alpine
    working_directory: ~/circleci-demo-workflows
    steps:
      - checkout
      - run:
          name: Install the Bundle Dependencies
          command: |
            gem install bundler
            bundle update --all --jobs 12
            bundle install --no-cache --jobs 8 --retry 3 --path vendor/bundle
      - run:
          name: Rake Test
          command: |
            bundle exec rake db:create db:schema:load
            bundle exec rake --trace
      - run:
          name: Check & Commit any Lockfile Updates
          command: |
            if [ -n "$(git status --porcelain | grep Gemfile)" ]; then
              git add Gemfile Gemfile.lock
              git commit --author "dependabot-bot <dependabot[bot]@users.noreply.github.com>" -m "Force Cron Update"
              git push -f origin master
              echo "Updated the master branch"
            else
              echo "Already Up2date with the upstream master"
            fi

  ruby24:
    docker:
      - image: circleci/ruby:2.4-node
      - image: circleci/postgres:9.4-alpine
    <<: *defaults

  ruby25:
    docker:
      - image: circleci/ruby:2.5-node
      - image: circleci/postgres:9.5-alpine
    <<: *defaults

  ruby26:
    docker:
      - image: circleci/ruby:2.6-node
      - image: circleci/postgres:9.5-alpine
    <<: *defaults

workflows:
  version: 2
  check_master_update:
    triggers:
       - schedule:
           cron: "0 0 * * *"
           filters:
             branches:
               only: master
    jobs:
      - master-ruby26
  build_dependabot_update:
    jobs:
      - ruby24:
          filters:
            branches:
              only: /dependabot.*/
      - ruby25:
          filters:
            branches:
              only: /dependabot.*/
      - ruby26:
          filters:
            branches:
              only: /dependabot.*/
